version : '3'
## Defining the containers
services:
  ## The first container is the CUDF container
  cudf_docker:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - "8888:8888"
    volumes:
      - /mnt/d/Dataset:/usr/app/Data
      - ./code_block:/usr/app/code_block
    environment:
      - DEBIAN_FRONTEND=noninteractive
    container_name: cudf_docker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    